Event driven powerups
theowiik/photon-phighters pull request #74
Opened 2023-06-10 14:01 UTC by erikwessman

Added some events and event handlers to do cool powerups.

How it works :nerd_face: :
1. The player does something 
2. The event is created, containing information about the event in the form of parameters that can be modified
3. Any powerup that is subscribed to the event modifies the event
4. Finally, the modified parameters in the event are used in whatever logic is needed

For example, in Fluorescent Burst (Getting hurt briefly increases movement speed):
The powerup subscribes to 2 events: when player 1 moves and when player 2 gets hurt
- If player 2 gets hurt we record the current elapsed time
- If player 1 moves and it has been less than X milliseconds since player 2 got hurt, we increase player 1 movement speed

2023-06-10 14:04 UTC, elias-carlson commented
Not checked the code but is the example correct? Isn't it supposed to increase the movement speed of the player who got hurt (player 2)?

2023-06-10 14:09 UTC, erikwessman commented
> Not checked the code but is the example correct? Isn't it supposed to increase the movement speed of the player who got hurt (player 2)?

Det där är fan sant. En sek

2023-06-10 14:45 UTC, theowiik commented on Photon Phighters.csproj
> +<Project Sdk="Godot.NET.Sdk/4.0.0">
Update Godot to 4.0.3 🤓 (download manually)

2023-06-10 16:14 UTC, theowiik requested changes

2023-06-10 16:14 UTC, theowiik commented on Scripts/Events/BulletEvents.cs
> +  public partial class BulletEvent : Node
There is only one event so we don't need the encapsulating class

2023-06-10 16:14 UTC, theowiik commented on Scripts/Events/GunEvents.cs
> +  public partial class ShootEvent : Node
Only one event, can remove the GunEvents class. Perhaps create a Events namespace?

2023-06-10 16:14 UTC, theowiik commented on Scripts/Events/BulletEvents.cs
> +    public BulletEvent(Area2D Area2D, Vector2 Velocity)
lowercase for parameters

2023-06-10 16:14 UTC, theowiik commented on Scripts/PowerUps.cs
> +      ulong CurrentTimeMsec = Time.GetTicksMsec();
var keyword

2023-06-10 16:14 UTC, theowiik commented on Scripts/PlayerMovementDelegate.cs
>    ///   The speed of which the player start taking damage from aerodynamic heating
The comment has lost its partner 😢

2023-06-11 19:19 UTC, theowiik commented on Scripts/PowerUps.cs
> +    private ulong _msecSinceLastWallJump;
Since all powerups only have one instance, they share this field, so the power up behaviours will be weird if both players have the same power up

2023-06-11 20:01 UTC, theowiik commented on Scripts/PowerUps.cs
> +    private ulong _msecSinceLastWallJump;
As this will require some relatively large changes, I can see us approving this PR and fix this separately

2023-06-12 15:43 UTC, merged